# NodePort: map containers port to localhost
service:
  type: NodePort
  # comment nodePorts to enable multi instances on local machine
  nodePorts:
    kwild: 32101
    kwil: 32102

kwild:
  hasura:
    postgresql:
      enabled: false
    service:
      type: NodePort
      # comment nodePorts to enable multi instances on local machine
      nodePorts:
        hasura: 32100
  image:
    repository: 358914811005.dkr.ecr.us-east-1.amazonaws.com/kwild
    pullPolicy: IfNotPresent
    tag: latest
  kwildApp:
    fund:
      #wallet: 274194b20d248d47c05913c039c65783647e527aa6360e5e143417f8bb50b988
      wallet: 30a4d9e36437d45e563b112ec38b8fc36c5aac80479fb3afce28022e4f3d74d7
      rpcUrl: wss://goerli.infura.io/ws/v3/745ef5cfaf9d405fb03b10a2c21d1f41
      publicRpcUrl: https://ethereum-goerli-rpc.allthatnode.com
      chainCode: 2
      blockConfirmation: 10
      poolAddress: 0xb0a194286A901FeAEA39D2b765247BEd64aD4F41
    log:
      level: debug
    gateway:
      # TODO: change to staging domain
      addr: "provider-test.kwil.com"

global:
  postgres:
    enabled: true # to use an exising database
    host: "kwildb-test-us-east-1.cluster-c4ahv6gbelvd.us-east-1.rds.amazonaws.com"
    port: 5432
    database: "postgres"
    username: "postgres"
    password: "postgres"

#Location of image in AWS ECR

image:
  repository: 358914811005.dkr.ecr.us-east-1.amazonaws.com/kwil-gateway
  pullPolicy: IfNotPresent
  tag: latest
