# trigger-test-kgw will run jobs when the CI workflow is successful
name: trigger-test-kgw

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

jobs:
  workflow-context: # for debugging
    name: Dump workflow context
    runs-on: ubuntu-latest
    steps:
      - name: Check if secret available
        run: |
          test ${{ secrets.KGW_MACH_SECRET_FOR_KWILDB }} = "" && echo "kgw access token empty" || echo "kgw access token available 1234"


  on-ci-success:
    # run when `CI` workflow is successful, not sure if this will work on forked PRs
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/kgw-test-reuse.yaml
    # https://github.com/GuillaumeFalourd/poc-github-actions/actions/runs/8534188213/job/23378138490
    # shows all the context available in the `workflow_run` event
    with:
      # use the branch from the `CI` workflow
      kdb-repo: ${{ github.event.workflow_run.repository.full_name }}
      kdb-sha: ${{ github.event.workflow_run.head_sha }}
      kdb-branch:  ${{ github.event.workflow_run.head_branch }}
      kgw-branch: main
    secrets:
      kgw-access-token: ${{ secrets.KGW_MACH_SECRET_FOR_KWILDB }}